services:
    app:
        build: .
        restart: unless-stopped
        container_name: lonipack-svelte
        environment:
            - PUBLIC_POCKETBASE_URL
        ports:
            - 3000:3000
