services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
            args:
                - PUBLIC_POCKETBASE_URL=$PUBLIC_POCKETBASE_URL
        restart: unless-stopped
        container_name: lonipack-svelte
        environment:
            - PUBLIC_POCKETBASE_URL
        ports:
            - 3000:3000
